version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/ec_site_on_rails
      - public-data:/ec_site_on_rails/public
      - tmp-data:/ec_site_on_rails/tmp
      - log-data:/ec_site_on_rails/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/ec_site_on_rails/public
      - tmp-data:/ec_site_on_rails/tmp
    ports:
      - 3000:3000
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
