version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/ec_site_on_rails
      - public-data:/ec_site_on_rails/public
      - tmp-data:/ec_site_on_rails/tmp
      - log-data:/ec_site_on_rails/log
    depends_on:
      - db
      - mongodb
    links:
      - redis:redis
    environment:
      - REDIS_URL=redis://redis:6379
      - MYSQL_HOST=db
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8
    # env_file:
    #   - ./environments/db.env
    environment:
      MYSQL_DATABASE: ec_site_on_rails_development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      -  'mongodb-data:/data/db'
    # command: mongod --smallfiles
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    links:
      - 'mongodb:mongo'
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/ec_site_on_rails/public
      - tmp-data:/ec_site_on_rails/tmp
    ports:
      - 3000:3000
    depends_on:
      - app
  redis:
    image: redis:2.8.13
    ports:
      - "6379:6379"
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
  mongodb-data: {}
