version: 2.1
jobs:
  build:
    docker:
    - image: circleci/ruby:2.7.3
      environment:
        - BUNDLER_VERSION: 2.2.17
        - RAILS_ENV: 'test'
    - image: circleci/mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD: password
        - MYSQL_DATABASE: ec_site_on_rails_test
        - MYSQL_USER: user
        - MYSQL_PASSWORD: password
        - MYSQL_ROOT_HOST: '127.0.0.1'

    working_directory: ~/ec_site_on_rails  #自身のアプリディレクトリ名を設定


    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "Gemfile.lock" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          gem install bundler -v 2.2.16
          bundle install --jobs=4 --retry=3 --path vendor/bundle

    - save_cache:
        paths:
        - ./vendor/bundle
        key: v1-dependencies-{{ checksum "Gemfile.lock" }}

    # Database setup
    - run: mv ./config/database.yml.ci ./config/database.yml

    # Database setup
    - run:
        name: Databasesetup
        command: |
           bundle exec rake db:create
           bundle exec rake db:schema:load

    # run tests!
    - run:
        name: run tests
        command: |
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
            circleci tests split --split-by=timings)"

          bundle exec rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress \
            $TEST_FILES

    # Rubocop
    - run:
        name: Rubocop
        command: bundle exec rubocop --fail-level W --display-only-fail-level-offenses

    # collect reports
    - store_test_results:
        path: /tmp/test-results
    - store_artifacts:
        path: /tmp/test-results
        destination: test-results
