default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'user' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: <%= ENV['MYSQL_HOST'] || 'localhost' %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: ec_site_on_rails_development

test:
  <<: *default
  database: ec_site_on_rails_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ec_site_on_rails_production
  username: user
  password: <%= ENV['DATABASE_PASSWORD'] %>
