# development:
#   fluent_host:   fluentd
#   fluent_port:   24224
#   tag:           'rails'
#   messages_type: 'string'
#
# test:
#   fluent_host:   '127.0.0.1'
#   fluent_port:   24224
#   tag:           'rails'
#   messages_type: 'string'
#
# production:
#   fluent_host:   '127.0.0.1'
#   fluent_port:   24224
#   tag:           'rails'
#   messages_type: 'string'
